export {
  initCrypto,
  Session,
  SessionState,
  SessionRole,
  SessionEvent,
  SessionController,
  type SessionConfig,
  type SessionEventMap,
  type PairingRequest,
  type ReceivedItem,
  type SentItem,
  type SessionSnapshot,
  WebSocketTransport,
  type WebSocketServerAdapter,
  type WebSocketClientAdapter,
  type ConnectionHandler,
  type ILocalTransport,
  type QrPayload,
  PROTOCOL_VERSION,
  DEFAULT_PORT,
  encodeQrPayload,
  decodeQrPayload,
  // config constants
  BOOTSTRAP_TTL,
  SESSION_TTL,
  SESSION_CODE_LENGTH,
  REGENERATION_DELAY_MS,
  COPY_FEEDBACK_MS,
  WS_CONNECT_TIMEOUT_MS,
  COUNTDOWN_INTERVAL_MS,
  CODE_PLACEHOLDER,
  // strings
  strings,
  // i18n
  en,
} from "@sharego/core";
