name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement. Please read the project invariants
        in docs/ARCHITECTURE.md and docs/REJECTED.md before submitting.

        Features that violate project invariants (cloud servers, internet fallback,
        more than 2 participants, etc.) will be closed immediately.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Affected Platforms
      description: Which platforms would this apply to?
      multiple: true
      options:
        - All platforms
        - macOS (Desktop)
        - Windows (Desktop)
        - Linux (Desktop)
        - Android (Mobile)
        - iOS (Mobile)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've thought about?
    validations:
      required: false
