export {
  initCrypto,
  Session,
  SessionState,
  SessionRole,
  SessionEvent,
  SessionController,
  type SessionConfig,
  type SessionEventMap,
  type PairingRequest,
  type ReceivedItem,
  type SentItem,
  type SessionSnapshot,
  WebSocketTransport,
  type WebSocketServerAdapter,
  type WebSocketClientAdapter,
  type ConnectionHandler,
  type ILocalTransport,
  type QrPayload,
  PROTOCOL_VERSION,
  DEFAULT_PORT,
  encodeQrPayload,
  decodeQrPayload,
  // config constants
  BOOTSTRAP_TTL,
  SESSION_TTL,
  SESSION_CODE_LENGTH,
  REGENERATION_DELAY_MS,
  COPY_FEEDBACK_MS,
  WS_CONNECT_TIMEOUT_MS,
  COUNTDOWN_INTERVAL_MS,
  CODE_PLACEHOLDER,
  DEVICE_NAME_RECEIVER,
  DEVICE_NAME_SENDER,
  // branded types
  type SessionId,
  type NetworkAddress,
  type Base64PublicKey,
  asSessionId,
  // discovery
  discoverReceiver,
  type DiscoveryOptions,
  // i18n
  en,
  // logger
  log,
  setLogger,
  type Logger,
} from "@sharego/core";
